//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalNews
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalNewsDBEntities : DbContext
    {
        public LocalNewsDBEntities()
            : base("name=LocalNewsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Login_History> Login_History { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<User_Status> User_Status { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<Security> Securities { get; set; }
    }
}
