//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalNews
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security
    {
        public long security_id { get; set; }
        public long user_id { get; set; }
        public long question_id { get; set; }
        public string answer { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
